#!/bin/sh

# basic config
layout=rivertile
browser=firefox
term=alacritty
launcher=fuzzel

RIVER_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/river"

riverctl border-width 2
riverctl border-color-focused 0xffffff
riverctl border-color-unfocused 0x000000

riverctl keyboard-layout pl
riverctl set-repeat 50 400
riverctl background-color 0x000000

riverctl spawn "dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn pipewire
riverctl spawn "wlr-randr --output HDMI-A-1 --mode 1920x1080@74.973Hz"

riverctl map normal Super Q close
riverctl map normal Super+Shift Q exit
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super Space toggle-float
riverctl map normal Super+Shift Return zoom

riverctl map normal Super Return spawn "$term"
riverctl map normal Super B spawn "$browser"
riverctl map normal Super E spawn "$launcher"
riverctl map normal None Print spawn "${RIVER_CONFIG_DIR}/scripts/sreenshot.sh"
riverctl map normal Shift Print spawn "${RIVER_CONFIG_DIR}/scripts/sreenshot.sh all"

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

for mode in normal locked; do
	riverctl map -repeat "$mode" None XF86AudioLowerVolume spawn "${RIVER_CONFIG_DIR}/scripts/volume.sh 5%-"
	riverctl map -repeat "$mode" None XF86AudioRaiseVolume spawn "${RIVER_CONFIG_DIR}/scripts/volume.sh 5%+"
	riverctl map "$mode" None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"

	riverctl map "$mode" None XF86AudioNext spawn "playerctl next"
	riverctl map "$mode" None XF86AudioPlay spawn "playerctl play-pause"
	riverctl map "$mode" None XF86AudioPrev spawn "playerctl previous"
done

for i in $(seq 9); do
	tag=$((1 << (i - 1)))
	riverctl map normal Super "$i" set-focused-tags "$tag"
	riverctl map normal Super+Shift "$i" set-view-tags "$tag"
	riverctl map normal Super+Control "$i" toggle-focused-tags "$tag"
	riverctl map normal Super+Shift+Control "$i" toggle-view-tags "$tag"
done

all_tags=$(((1 << 9) - 1))
riverctl map normal Super 0 set-focused-tags "$all_tags"
riverctl map normal Super+Shift 0 set-view-tags "$all_tags"

scratch_tag=$((1 << 9))
riverctl map normal Super Minus toggle-focused-tags "$scratch_tag"
riverctl map normal Super+Shift Minus set-view-tags "$scratch_tag"

riverctl default-layout "$layout"
case "$layout" in
rivertile)
	riverctl spawn rivertile
	riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
	riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
	riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
	riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

	riverctl map normal Super+Shift+Control H send-layout-cmd rivertile "main-location left"
	riverctl map normal Super+Shift+Control J send-layout-cmd rivertile "main-location bottom"
	riverctl map normal Super+Shift+Control K send-layout-cmd rivertile "main-location top"
	riverctl map normal Super+Shift+Control L send-layout-cmd rivertile "main-location right"
	;;
luatile)
	riverctl spawn river-luatile
	;;
esac

# vim:noet
